= Hashmaps for Scheme

An implementation of hash array mapped tries for Scheme. The maps may
be used _in-place_. However, all operations that modify the map
in-place return the map as value, so code can be written as if the map
were ‘linear updating’. The maps may also be used as _persistent_ data
structures.footnote:[Such structures are often called ‘immutable’, but
I think ‘persistent’ is a better name. The structure may change
internally, but its past states _effectively persist_ until no longer
needed.]

There are interfaces for R⁶RS, R⁷RS, Gambit Scheme (as an R⁷RS
library), CHICKEN 5 Scheme (using the ‘r7rs’ egg), and CHICKEN 6
Scheme (as an R⁷RS library).

There is a makefile for GNU Make, with targets for testing with
various Scheme implementations. The makefile has targets
_install-chicken-5-egg_ and _install-chicken-6-egg_ to install CHICKEN
eggs (using _sudo_ privileges for installation). There are
corresponding targets _uninstall-chicken-5-egg_ and
_uninstall-chicken-6-egg_. The egg is called *hashassoc*. There are
also targets _install-chez_ and _uninstall-chez_ for Chez Scheme, with
both source and pre-compiled code going in the directory specified by
the makefile variable _CHEZSCHEME_INSTALLDIR_.

Import the library as *(hashassoc)*. The following procedures are
provided.footnote:[To avoid confusion with SRFI-146, the procedure
names are made from ‘_hashassoc_’ instead of ‘_hashmap_’.] Hash
functions passed as arguments must return a nonnegative fixnum.
Comparator objects passed as arguments are those of SRFI-128, and the
outputs of their hash functions will be truncated to fixnums.

*(make-hashassoc _equiv?_ _hashfunc_ _key1_ _value1_ ...)*:: Make a
    new hashmap from a key-equivalence procedure,footnote:equiv[The
    key-equivalence procedure takes the _stored_ key as its _second_
    argument.] a key-hash procedure, and the given keys and values.
    Key-value pairs earlier in the sequence have precedence.
*(make-hashassoc _comparator_ _key1_ _value1_ ...)*:: Make a new
    hashmap from a comparator and the given keys and values. Key-value
    pairs earlier in the sequence have precedence.
*(alist*+->+*hashassoc _equiv?_ _hashfunc_ _alist_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and an association list. Key-value pairs
    earlier in the sequence have precedence.
*(alist*+->+*hashassoc _comparator_ _alist_)*:: Make a new hashmap
    from a comparator and an association list. Key-value pairs earlier
    in the sequence have precedence.
*(hashassoc*+->+*alist _hashmap_)*:: Return an association list
    containing, in any order, the same key-value pairs as the hashmap.
*(vector*+->+*hashassoc _equiv?_ _hashfunc_ _vector_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and a vector of key-value pairs. Key-value
    pairs earlier in the sequence have precedence.
*(vector*+->+*hashassoc _comparator_ _vector_)*:: Make a new hashmap
    from a comparator and a vector of key-value pairs. Key-value pairs
    earlier in the sequence have precedence.
*(hashassoc*+->+*vector _hashmap_)*:: Return a vector containing, in
    any order, the same key-value pairs as the hashmap.
*(hashassoc-copy _hashmap_)*:: Make a structural copy of a hashmap.
     The copy is _complete_: even the pairs are replaced. The keys and
     values are the only objects not copied.
*(hashassoc*+->+*generator _hashmap_)*:: Return a thunk that
     generates, in any order, the key-value pairs that are contained
     in the hashmap. Once all the key-value pairs have been produced,
     end-of-file objects are generated, instead.
*(hashassoc-fold _kons_ _knil_ _hashmap_)*:: Walk the hashmap in any
     order. Return the result of _(kons pairₙ (...(kons pair₁ (kons
     pair₀ knil))...))_
*(hashassoc? _object_)*:: Is the given object a hashmap? +#t+ or +#f+
*(hashassoc-size _hashmap_)*:: Return the number of key-value pairs
     stored in the hashmap.
*(hashassoc-empty? _hashmap_)*:: Is the number of key-value pairs in the
     hashmap equal to zero? +#t+ or +#f+
*(hashassoc-ref _hashmap_ _key_)*:: Try to retrieve a key-value pair
     from the hashmap. If there is failure to find the key in the map,
     then return +#f+. If there is success, return not merely the
     value, but a _cons-pair_, containing both the _stored_ key and
     its corresponding value. This convention for return values makes
     it unambiguous whether retrieval is successful.
*(hashassoc-set! _hashmap_ _key1_ _value1_ ...)*:: Either insert or
     replace hashmap entries.
*(hashassoc-set-from-alist! _hashmap_ _alist_)*:: Either insert or
     replace hashmap entries, taking the new key-value pairs from an
     association list.
*(hashassoc-set _hashmap_ _key_ _value_)*:: Either insert or replace a
     hashmap entry, in a _persistent data structures_ fashion. Returns
     a new hashmap that may share structure with the old one.
*(hashassoc-insert! _hashmap_ _key1_ _value1_ ...)*:: Insert, but do
     not replace, hashmap entries.
*(hashassoc-insert-from-alist! _hashmap_ _alist_)*:: Insert, but do
     not replace, hashmap entries, taking the new key-value pairs from
     an association list.
*(hashassoc-insert _hashmap_ _key_ _value_)*:: Insert, but do not
     replace, a hashmap entry, in a _persistent data structures_
     fashion. Returns a new hashmap that may share structure with the
     old one.
*(hashassoc-replace! _hashmap_ _key1_ _value1_ ...)*:: Replace, but do
     not insert, hashmap entries.
*(hashassoc-replace-from-alist! _hashmap_ _alist_)*:: Replace, but do
     not insert, hashmap entries, taking the new key-value pairs from
     an association list.
*(hashassoc-replace _hashmap_ _key_ _value_)*:: Replace, but do not
     insert, a hashmap entry, in a _persistent data structures_
     fashion. Returns a new hashmap that may share structure with the
     old one.
*(hashassoc-delete! _hashmap_ _key1_ ...)*:: For every given key, if
     it is contained in the hashmap, delete the corresponding
     key-value associaition.
*(hashassoc-delete-from-list! _hashmap_ _list_)*:: For every key in
     the given list, if the key is contained in the hashmap, delete
     the corresponding key-value association.
*(hashassoc-delete _hashmap_ _key_)*:: If the given key is found in
     the hashmap, delete the corresponding key-value association, in a
     _persistent data structures_ fashion. Returns a new hashmap that
     may share structure with the old one.
*(hashassoc-union _hashmap1_ ...)*:: Copy the first hashmap listed.
     Then successively insert entries from the other hashmaps listed.
     Do not replace any already inserted entries. This operation is
     analogous to a set union.
*(hashassoc-add! _hashmap1_ ...)*:: Successively insert into
     _hashmap1_ entries from the other hashmaps listed. Do not replace
     any already inserted entries.footnote:[The name
     *hashassoc-union!* would be unintuitive for an in-place
     procedure.]
*(hashassoc-intersection _hashmap1_ ...)*:: Copy the first hashmap
     listed. Then delete any entries whose keys are not found in the
     other hashmaps listed. This operation is analogous to a set
     intersection.
*(hashassoc-intersect! _hashmap1_ ...)*:: Delete from _hashmap1_ any
     entries whose keys are not found in the other hashmaps
     listed.footnote:[The name *hashassoc-intersection!* would be
     unintuitive for an in-place procedure.]
*(hashassoc-difference _hashmap1_ ...)*:: Copy the first hashmap
     listed. Then delete any entries whose keys are found in the other
     hashmaps listed. This operation is analogous to a set difference.
*(hashassoc-subtract! _hashmap1_ ...)*:: Delete from _hashmap1_ any
     entries whose keys are found in the other hashmaps
     listed.footnote:[The name *hashassoc-difference!* would be
     unintuitive for an in-place procedure.]
*(hashassoc-symmetric-difference _hashmap1_ _hashmap2_)*:: Return a
     structurally entirely new hashmap whose key-value associations
     are those of _hashmap1_ not found in _hashmap2_ and those of
     _hashmap2_ not found in _hashmap1_.
*(hashassoc-disjoint? _hashmap1_ _hashmap2_)*:: Return +#t+ if the two
     hashmaps have no keys in common. Otherwise return +#f+.
*(hashassoc=? [#f|#t|_value-equiv=?_] _hashmap1_ ...)*::
*(hashassoc*+<+*? [#f|#t|_value-equiv=?_] _hashmap1_ ...)*::
*(hashassoc*+<=+*? [#f|#t|_value-equiv=?_] _hashmap1_ ...)*::
*(hashassoc*+>+*? [#f|#t|_value-equiv=?_] _hashmap1_ ...)*::
*(hashassoc*+>=+*? [#f|#t|_value-equiv=?_] _hashmap1_ ...)*::
     Boolean-valued procedures analogous to subset and superset
     relations. Each hashmap listed must have the same key-equivalence
     procedure, or the return value is +#f+. The sizes of the listed
     hashmaps must be monotone according to the name of the procedure,
     or the return value is +#f+. Otherwise all adjacent pairs of
     hashmaps are compared in the following fashion. For each entry in
     the ‘smaller’ (possibly actually equal-sized) hashmap of the two,
     there must be an entry with matching key, in the other hashmap.
     Then the two entries must match in their value field, as well. If
     a _value-equiv?_ procedure is given, that is used, with its two
     value arguments left-to-right according to the the order in which
     the hashmaps are listed. If either +#f+ or +#t+ is given, then
     the values are not compared and only the keys are relevant. If
     none of these is given, then *equal?* is used as the
     _value-equiv=?_ procedure.

***

A SRFI-42-style interface is available as *(hashassoc
eager-comprehensions)*. (See below for how to use the interface with
Gambit Scheme.) The library exports many SRFI-42 symbols, but not
those concerning dispatched generators. (Dispatched generators are
problematic in Schemes with module systems.) For some Scheme
implementations the symbols are reëxported from a SRFI-42 library,
whereas for others they are exported from our own copy of the SRFI-42
reference code. It depends mainly on whether we think the external
SRFI-42 library is broken, which we often do.

The SRFI-42 interface is extended with the following syntax:

*(hashassoc-ec _comparator_ _qualifier1_ ... _expression_)*::
     _Comprehension_. The expression for this comprehension must
     supply key-value pairs. Pairs generated earlier have precedence.
*(:hashassoc-pairs  _var_ _hashmap1_ ...)*::
*(:hashassoc-keys   _var_ _hashmap1_ ...)*::
*(:hashassoc-values _var_ _hashmap1_ ...)*::
*(:hashassoc-pairs  _var1_ (index _var2_) _hashmap1_ ...)*::
*(:hashassoc-keys   _var1_ (index _var2_) _hashmap1_ ...)*::
*(:hashassoc-values _var1_ (index _var2_) _hashmap1_ ...)*::
     _Generators_. If more than one hashmap is listed, the hashmaps
     are gone through in sequence. They need not all have the same key
     and value types.

In Gambit Scheme, you cannot import *(hashassoc
eager-comprehensions)*. Also, SRFI-128 is available from Snow under
the name *comparators* rather than *(srfi 128)*. Thus, instead install
comparators with

----
snow-chibi install --impls gambit comparators
----

and put something like this in your code:

[source,scheme]
----
(import (comparators))
(include "hashassoc/ec.scm")
(include "hashassoc/eager-comprehensions-implementation.scm")
----

The _hashassoc/ec.scm_ file is based closely on the reference sources
for SRFI-42, and is more reliable than getting SRFI-42 support from
elsewhere.
