= Hashmaps for Scheme

An implementation of hash array mapped tries for Scheme. The maps are
mutable and in-place.footnote:[Implementing SRFI-146 hashmaps with
this package would require often using _hashassoc-copy_ to copy the
whole structure. SRFI-146 effectively presumes—though carefully does
not require—a persistent structure: one whose operations do not alter
what is already written. Operations that do not copy the whole
structure might be added at some point. However, a non-persistent
hashmap is inherently useful, and this implementation works
_in-place_, which can be convenient. What one _can_ do is use the
interface of SRFI-146 but not substitute a Scheme’s default
implementation with this, or one can simply not use a SRFI-146
interface.] However, all operations that modify the map return the map
as value, so code can be written as if the map were ‘linear
updating’.footnote:[I have long had an ATS2 implementation of hash
tries. Once translated from ATS2, the code can be compiled with just a
C compiler and some special headers. The ATS2 source code employs
linear types and typechecking-time proofs for safety and requires only
that stored objects be allocated to fixed locations, in the manner of
a malloc. Garbage collection is not required, nor reference-counting,
nor is any non-C runtime support needed. I may one day add this
implementation as FFI for compatible Schemes. It is this ATS2
implementation that inspired me to implement non-persistent hashmaps.
Indeed, to copy the ATS2 structure for SRFI-146 will require totally
bypassing typesafety. It is lack of a linear type system, in which an
object may be referred to only once at a time, that makes mutability
(potentially) hazardous. Persistence, on the other hand, almost forces
us to use a garbage collector or reference-counting. If one had to
manually keep track of and free obsolete portions of structures,
programming might become overwhelmingly burdensome.]

There are interfaces for R⁶RS, R⁷RS, Gambit Scheme (as an R⁷RS
library), CHICKEN 5 Scheme (using the ‘r7rs’ egg), and CHICKEN 6
Scheme (as an R⁷RS library).

The following procedures are provided.footnote:[To avoid confusion
with SRFI-146, the procedure names are made from ‘_hashassoc_’ instead
of ‘_hashmap_’.] Hash functions passed as arguments must return a
nonnegative fixnum. Comparator objects passed as arguments are those
of SRFI-128, and the outputs of their hash functions will be truncated
to fixnums.

*(make-hashassoc _equiv?_ _hashfunc_ _key1_ _value1_ ...)*::
    Make a new hashmap from a key-equivalence
    procedure,footnote:equiv[The key-equivalence procedure takes the
    _stored_ key as its _second_ argument.] a key-hash procedure, and
    the given keys and values.
*(make-hashassoc _comparator_ _key1_ _value1_ ...)*:: Make a new
    hashmap from a comparator and the given keys and values.
*(alist*+->+*hashassoc _equiv?_ _hashfunc_ _alist_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and an association list.
*(alist*+->+*hashassoc _comparator_ _alist_)*:: Make a new hashmap
    from a comparator and an association list.
*(hashassoc*+->+*alist _hashmap_)*:: Return an association list
    containing, in any order, the same key-value pairs as the hashmap.
*(vector*+->+*hashassoc _equiv?_ _hashfunc_ _vector_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and a vector of key-value pairs.
*(vector*+->+*hashassoc _comparator_ _vector_)*:: Make a new hashmap
    from a comparator and a vector of key-value pairs.
*(hashassoc*+->+*vector _hashmap_)*:: Return a vector containing, in
    any order, the same key-value pairs as the hashmap.
*(hashassoc-copy _hashmap_)*:: Make a structural copy of a hashmap.
     The copy is _complete_: even the pairs are replaced. The keys and
     values are the only objects not copied.
*(hashassoc*+->+*generator _hashmap_)*:: Return a thunk that
     generates, in any order, the key-value pairs that are contained
     in the hashmap. Once all the key-value pairs have been produced,
     end-of-file objects are generated, instead.
*(hashassoc-fold _kons_ _knil_ _hashmap_)*:: Walk the hashmap in any
     order. Return the result of _(kons pairₙ (...(kons pair₁ (kons
     pair₀ knil))...))_
*(hashassoc? _object_)*:: Is the given object a hashmap? +#t+ or +#f+
*(hashassoc-size _hashmap_)*:: Return the number of key-value pairs
     stored in the hashmap.
*(hashassoc-empty? _hashmap_)*:: Is the number of key-value pairs in the
     hashmap equal to zero? +#t+ or +#f+
*(hashassoc-ref _hashmap_ _key_)*:: Try to retrieve a key-value pair
     from the hashmap. If there is failure to find the key in the map,
     then return +#f+. If there is success, return not merely the
     value, but a _cons-pair_, containing both the _stored_ key and
     its corresponding value. This convention for return values makes
     it unambiguous whether retrieval is successful.
*(hashassoc-set! _hashmap_ _key1_ _value1_ ...)*:: Either insert or
     replace hashmap entries.
*(hashassoc-set-from-alist! _hashmap_ _alist_)*:: Either insert or
     replace hashmap entries, taking the new key-value pairs from an
     association list.
*(hashassoc-insert! _hashmap_ _key1_ _value1_ ...)*:: Insert, but do
     not replace, hashmap entries.
*(hashassoc-insert-from-alist! _hashmap_ _alist_)*:: Insert, but do
     not replace, hashmap entries, taking the new key-value pairs from
     an association list.
*(hashassoc-replace! _hashmap_ _key1_ _value1_ ...)*:: Replace, but do
     not insert, hashmap entries.
*(hashassoc-replace-from-alist! _hashmap_ _alist_)*:: Replace, but do
     not insert, hashmap entries, taking the new key-value pairs from
     an association list.
*(hashassoc-delete! _hashmap_ _key1_ ...)*:: For every given key, if
     it is contained in the hashmap, delete the corresponding
     key-value pair.
*(hashassoc-delete-from-list! _hashmap_ _list_)*:: For every key in the
     given list, if the key is contained in the hashmap, delete the
     corresponding key-value pair.
*(hashassoc-union _hashmap1_ ...)*:: Copy the first hashmap listed.
     Then successively insert entries from the other hashmaps listed.
     Do not replace any already inserted entries. This operation is
     analogous to a set union.
*(hashassoc-add! _hashmap1_ ...)*:: Successively insert into
     _hashmap1_ entries from the other hashmaps listed. Do not replace
     any already inserted entries.footnote:[The name
     *hashassoc-union!* would be unintuitive for an in-place
     procedure.]
*(hashassoc-intersection _hashmap1_ ...)*:: Copy the first hashmap
     listed. Then delete any entries whose keys are not found in the
     other hashmaps listed. This operation is analogous to a set
     intersection.
*(hashassoc-intersect! _hashmap1_ ...)*:: Delete from _hashmap1_ any
     entries whose keys are not found in the other hashmaps
     listed.footnote:[The name *hashassoc-intersection!* would be
     unintuitive for an in-place procedure.]
*(hashassoc-difference _hashmap1_ ...)*:: Copy the first hashmap
     listed. Then delete any entries whose keys are found in the other
     hashmaps listed. This operation is analogous to a set difference.
*(hashassoc-subtract! _hashmap1_ ...)*:: Delete from _hashmap1_ any
     entries whose keys are found in the other hashmaps
     listed.footnote:[The name *hashassoc-difference!* would be
     unintuitive for an in-place procedure.]
*(hashassoc-symmetric-difference _hashmap1_ _hashmap2_)*:: Return a
     structurally entirely new hashmap whose key-value associations
     are those of _hashmap1_ not found in _hashmap2_ and those of
     _hashmap2_ not found in _hashmap1_.
