= Hashmaps for Scheme

An implementation of hash array mapped tries for Scheme. The maps are
mutable and in-place.footnote:[Implementing SRFI-146 hashmaps with
this package would often require copying the whole structure, though
not the keys and values. SRFI-146 effectively presumes—though
carefully does not require—a persistent structure: one whose
operations do not alter what is already written. Operations that do
not copy the whole structure might be added at some point. However, a
non-persistent hashmap is inherently very useful. What one _can_ do is
provide the interface of SRFI-146 but not make this implementation a
Scheme’s default one.] However, all operations that modify the map
return the map as value, so code can be written as if the map were
‘linear updating’.footnote:[I have long had an ATS2 implementation of
hash tries. Once translated from ATS2, the code can be compiled with
just a C compiler and some special headers. The ATS2 source code
employs linear types and typechecking-time proofs for safety and
requires only that stored objects be allocated to fixed locations, in
the manner of a malloc. Garbage collection is not required, nor is any
non-C runtime support needed. I may one day add this implementation as
FFI for compatible Schemes. It is this ATS2 implementation that
inspired me to implement non-persistent hashmaps. Indeed, to copy the
ATS2 structure for SRFI-146 will require totally bypassing typesafety.
It is lack of a linear type system, in which an object may be referred
to only once at a time, that makes mutability (potentially) hazardous.
Persistence, on the other hand, almost forces us to use a garbage
collector. If one had to keep track of and free persistent structure
versions manually, programming might become overwhelmingly
burdensome.]

There are interfaces for R⁶RS, R⁷RS, Gambit Scheme (as an R⁷RS
library), CHICKEN 5 Scheme (using the ‘r7rs’ egg), and CHICKEN 6
Scheme (as an R⁷RS library).

The following procedures are provided. Hash functions passed as
arguments must return a nonnegative fixnum. Comparator objects passed
as arguments are those of SRFI-128, and the outputs of their hash
functions will be truncated to fixnums.

*(make-hashmap _equiv?_ _hashfunc_ _key1_ _value1_ ...)*::
    Make a new hashmap from a key-equivalence
    procedure,footnote:equiv[The key-equivalence procedure takes the
    _stored_ key as its _second_ argument.] a key-hash procedure, and
    the given keys and values.
*(make-hashmap _comparator_ _key1_ _value1_ ...)*:: Make a new hashmap
    from a comparator and the given keys and values.
*(alist*+->+*hashmap _equiv?_ _hashfunc_ _alist_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and an association list.
*(alist*+->+*hashmap _comparator_ _alist_)*:: Make a new hashmap from
    a comparator and an association list.
*(hashmap*+->+*alist _hashmap_)*:: Return an association list
    containing, in any order, the same key-value pairs as the hashmap.
*(vector*+->+*hashmap _equiv?_ _hashfunc_ _vector_)*:: Make a new
    hashmap from a key-equivalence procedure,footnote:equiv[] a
    key-hash procedure, and a vector of key-value pairs.
*(vector*+->+*hashmap _comparator_ _vector_)*:: Make a new hashmap
    from a comparator and a vector of key-value pairs.
*(hashmap*+->+*vector _hashmap_)*:: Return a vector containing, in any
    order, the same key-value pairs as the hashmap.
*(hashmap*+->+*generator _hashmap_)*:: Return a thunk that generates,
     in any order, the key-value pairs that are contained in the
     hashmap. Once all the key-value pairs have been produced,
     end-of-file objects are generated, instead.
*(hashmap-fold _kons_ _knil_ _hashmap_)*:: Walk the hashmap in any
     order. Return the result of _(kons pairₙ (...(kons pair₁ (kons
     pair₀ knil))...))_
*(hashmap? _object_)*:: Is the given object a hashmap? +#t+ or +#f+
*(hashmap-size _hashmap_)*:: Return the number of key-value pairs
     stored in the hashmap.
*(hashmap-empty? _hashmap_)*:: Is the number of key-value pairs in the
     hashmap equal to zero? +#t+ or +#f+
*(hashmap-ref _hashmap_ _key_)*:: Try to retrieve a key-value pair
     from the hashmap. If there is failure to find the key in the map,
     then return +#f+. If there is success, return not merely the
     value, but a _cons-pair_, containing both the _stored_ key and
     its corresponding value. This convention for return values makes
     it unambiguous whether retrieval is successful.
*(hashmap-set! _hashmap_ _key1_ _value1_ ...)*:: Either insert or
     replace hashmap entries.
*(hashmap-set-from-alist! _hashmap_ _alist_)*:: Either insert or
     replace hashmap entries, taking the new key-value pairs from an
     association list.
*(hashmap-delete! _hashmap_ _key1_ ...)*:: For every given key, if it
     is contained in the hashmap, delete the corresponding key-value
     pair.
*(hashmap-delete-from-list! _hashmap_ _list_)*:: For every key in the
     given list, if the key is contained in the hashmap, delete the
     corresponding key-value pair.
